CREATE TABLE clientes (id BIGINT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(120) NOT NULL,correo VARCHAR(120),telefono VARCHAR(40));
CREATE TABLE productos (id BIGINT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(120) NOT NULL,precio DECIMAL(12,2) NOT NULL,stock INT NOT NULL);
CREATE TABLE ventas (id BIGINT AUTO_INCREMENT PRIMARY KEY,cliente_id BIGINT NOT NULL,producto_id BIGINT NOT NULL,cantidad INT NOT NULL,total DECIMAL(12,2) NOT NULL,fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
